#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

exposed_version=0.61.0
h2_version=2.3.232
kotlin_version=2.3.0
ktor_version=3.4.2
logback_version=1.4.14